server:
  port: 8081

app:
  kafka:
    orderTopic: "order-topic"
    orderStatusTopic: "order-status-topic"

spring:
  kafka:
    consumer:
      group-id: "order-status-service-group"
      auto-offset-reset: "earliest"
      bootstrap-servers: "localhost:9092"
    producer:
      bootstrap-servers: "localhost:9092"